### PR TITLE
add snappy and zstd compression type support

### PR DESCRIPTION
**Pull request by a-beloglazov**

### CODE REVIEW

**Comment by ivanyu** [comment]
Overall LGTM, but let's merge the CI PR first

**Comment by ivanyu** [comment]
Fails on my machine with 
```
* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve io.aiven:aiven-kafka-connect-commons:0.0.14.
     Required by:
         project :
      > Could not resolve io.aiven:aiven-kafka-connect-commons:0.0.14.
         > Could not get resource 'https://maven.pkg.github.com/aiven/aiven-kafka-connect-commons/io/aiven/aiven-kafka-connect-commons/0.0.14/aiven-kafka-connect-commons-0.0.14.pom'.
            > Username must not be null!
```
The POM file doesn't seem to be accessible without authentication. Could you please check?

**Comment by a-beloglazov** [comment]
Problem was solved by replacing GitHub Packages to Bintray.

**Review by ivanyu — APPROVED** [review]

**Review by ivanyu — CHANGES_REQUESTED** [review]
LGTM.
Could you also refresh the README regarding this?

**Review by ivanyu — APPROVED** [review]

**Pull request merged**
